Linear Algebra in Python

In [1]:
import numpy as np

In [2]:
v1=np.array([1,2,3])# A 3D Vector
v2=np.array([4,5,6])# Another 3D Vector

In [3]:
print(v1)
print(v2)

[1 2 3]
[4 5 6]


In [6]:
v_add=v1+v2
v_sub=v1-v2

In [8]:
print(v_add)
print(v_sub)

[5 7 9]
[-3 -3 -3]


In [9]:
scale = 2
v_scale = scale*v1

In [11]:
print(v_scale)

[2 4 6]


In [12]:
dot_prod=np.dot(v1,v2)

In [13]:
print(dot_prod)

32


In [14]:
mag=np.linalg.norm(v1)

In [15]:
print("Magnitude of V1:", mag)

Magnitude of V1: 3.7416573867739413


In [20]:
A=np.array([[1,2,3],[4,5,6]])
print(A)
print()

B=np.array([[7,8,9],[10,11,12],[13,14,15]])
print(B)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [26]:
C=np.array([[1,2,3],[4,5,6]])
matrix_add=A+C
matrix_sub=A-C

print("A+C=\n", matrix_add)
print("A-C=\n", matrix_sub)

A+C=
 [[ 2  4  6]
 [ 8 10 12]]
A-C=
 [[0 0 0]
 [0 0 0]]


In [28]:
matrix_mul=np.dot(A,B)
print(matrix_mul)

[[ 66  72  78]
 [156 171 186]]


In [29]:
transpose_A = A.T
print("Transpose of A:\n", transpose_A)

Transpose of A:
 [[1 4]
 [2 5]
 [3 6]]


In [30]:
a=np.array([[2,3],[4,-1]])
b=np.array([5,3])
print(a)
print()
print(b)
x=np.linalg.solve(a,b)
print(x)

[[ 2  3]
 [ 4 -1]]

[5 3]
[1. 1.]


In [32]:
A=np.array([[2,1],[1,2]])
e_val,e_vec=np.linalg.eig(A) # 2 values because it returns 2 values

In [33]:
print("Eval:",e_val)
print("Evec:",e_vec)

Eval: [3. 1.]
Evec: [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [34]:
A = np.array([[4, 7], [2, 6]])

A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)

identity = np.dot(A, A_inv)
print("A * A_inv:\n", identity)

Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
A * A_inv:
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
